name: Release


on:
  workflow_dispatch:
    inputs:
      release:
        description: Is release? (Will update master version.txt)
        required: true
        default: false
        type: boolean
      tagged-version:
        description: Release Version (For tagged version.txt)
        required: true
        type: string
      new-version:
        description: New Version (For branch version.txt)
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'

jobs:
  tag-release:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: update-tag
        if: ${{ inputs.release }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions"
          echo ${{ inputs.tagged-version }} > version.txt
          git add version.txt
          git status
          git commit -m "${{ inputs.tagged-version }} released."
          git tag ${{ inputs.tagged-version }}
          git push 
          git push origin refs/tags/${{ inputs.tagged-version }}

  build-java:
    permissions:
      contents: write
      packages: write
    needs: tag-release
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        repo: ['public', 'private']
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV
      - name: Publish with Gradle to Open Source
        if: ${{ matrix.repo == 'public' }}
        run: ./gradlew publishAllPublicationsToOssRepository
        env:
          ORG_GRADLE_PROJECT_repoUsername: ${{ secrets.osshrUsername }}
          ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.osshrPassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
      #      - name: install-sshpass
      #        if: ${{ matrix.repo == 'private' }}
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get -y install sshpass
      - name: get-cme-ilink
        if: ${{ matrix.repo == 'private' }}
        run: sshpass -p "$CME_PASSWORD" scp cmeconfig@sftpng.cmegroup.com:/MSGW/Production/Templates/ilinkbinary_v7.xml artio-ilink3-codecs/src/main/resources/uk/co/real_logic/artio/ilink/ilinkbinary.xml
        env:
          CME_PASSWORD: ${{ secrets.cmePassword }}
      - name: Publish with Gradle to Private Repo
        if: ${{ matrix.repo == 'private' }}
        run: ./gradlew -Dfix.core.iLink3Enabled=true publishAllPublicationsToPrivateRepository
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretAccessKey }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}

  update-tags:
    permissions:
      contents: write
    needs: build-java
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: update-branch
        if: ${{ inputs.release }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions"
          echo ${{ inputs.new-version }} > version.txt
          git add version.txt
          git status
          git commit -m "${{ inputs.tagged-version }} released."
          git push