name: Release


on:
  workflow_dispatch:
    inputs:
      run-ci:
        description: Run ci and test workflows
        required: true
        type: boolean
      release:
        description: Is release? (Will update tags and version)
        required: true
        default: false
        type: boolean
      release-version:
        description: Released version (x.y.z)
        required: true
        type: string
      next-version:
        description: Next version (x.y.z)
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'

jobs:
  run-release-ci:
    name: Run ci workflows
    uses: ./.github/workflows/pre-release-ci.yml
    with:
      run-ci: ${{ inputs.run-ci }}
      codeql: ${{ inputs.run-ci }}

  pre-release:
    name: Update version, tag repo, and return sha
    needs: run-release-ci
    uses: ./.github/workflows/pre-release.yml
    with:
      release: ${{ inputs.release }}
      version: ${{ inputs.release-version }}

  release:
    name: Release java artifacts
    permissions:
      contents: write
      packages: write
    needs: pre-release
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        repo: ['public', 'private']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.pre-release.outputs.sha }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV
      - name: Publish with Gradle to Open Source
        if: ${{ matrix.repo == 'public' }}
        run: ./gradlew publishAllPublicationsToOssRepository
        env:
          ORG_GRADLE_PROJECT_repoUsername: ${{ secrets.osshrUsername }}
          ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.osshrPassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
      #      - name: install-sshpass
      #        if: ${{ matrix.repo == 'private' }}
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get -y install sshpass
      - name: Get CME ILink3 XML Schema
        if: ${{ matrix.repo == 'private' }}
        run: sshpass -p "$CME_PASSWORD" scp cmeconfig@sftpng.cmegroup.com:/MSGW/Production/Templates/ilinkbinary_v7.xml artio-ilink3-codecs/src/main/resources/uk/co/real_logic/artio/ilink/ilinkbinary.xml
        env:
          CME_PASSWORD: ${{ secrets.cmePassword }}
      - name: Publish with Gradle to Private Repo
        if: ${{ matrix.repo == 'private' }}
        run: ./gradlew -Dfix.core.iLink3Enabled=true publishAllPublicationsToPrivateRepository
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretAccessKey }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}

  post-release:
    name: Update version
    needs: release
    uses: ./.github/workflows/post-release.yml
    with:
      release: ${{ inputs.release }}
      version: ${{ inputs.next-version }}